add secrets use

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -34,23 +34,26 @@ jobs:
           echo "Killing all running Java processes..."
           pkill -f java || echo "No Java processes running."
 
-      - name: Start application in background
-        run: |
-          echo "Starting application in background with nohup..."
-          nohup java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
-          
-      - name: Start Check
-        env:
-          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
-        run: |
-          echo "Performing health check..."
-          sleep 20  # Letting the app to start
-          if pgrep -f memory-cards-0.0.1-SNAPSHOT.jar > /dev/null; then
-            echo "Application is running."
-          else
-            echo "Application failed to start."
-            exit 1
-          fi
+      - name: Run in a job (to be removed)
+        run: java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar
+#
+#      - name: Start application in background
+#        run: |
+#          echo "Starting application in background with nohup..."
+#          nohup java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
+#
+#      - name: Start Check
+#        env:
+#          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
+#        run: |
+#          echo "Performing health check..."
+#          sleep 20  # Letting the app to start
+#          if pgrep -f memory-cards-0.0.1-SNAPSHOT.jar > /dev/null; then
+#            echo "Application is running."
+#          else
+#            echo "Application failed to start."
+#            exit 1
+#          fi
 
   build:
     runs-on: self-hosted
