add start check

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -38,6 +38,17 @@ jobs:
         run: |
           echo "Starting application in background with nohup..."
           nohup java -jar build/libs/memory-cards-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
+          
+      - name: Start Check
+        run: |
+          echo "Performing health check..."
+          sleep 20  # Letting the app to start
+          if pgrep -f memory-cards-0.0.1-SNAPSHOT.jar > /dev/null; then
+            echo "Application is running."
+          else
+            echo "Application failed to start."
+            exit 1
+          fi
 
   build:
     runs-on: self-hosted
