split jobs

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -40,44 +40,44 @@ jobs:
     - name: Copy JAR to /tmp
       run: cp build/libs/memory-cards-0.0.1-SNAPSHOT.jar /tmp/
 
-    run-app:
-      needs: build
-      runs-on: self-hosted
-      permissions:
-        contents: read
+  run-app:
+    needs: build
+    runs-on: self-hosted
+    permissions:
+      contents: read
 
-      steps:
-        - name: Verify JAR existence in /tmp
-          run: ls -l /tmp/memory-cards-0.0.1-SNAPSHOT.jar
+    steps:
+      - name: Verify JAR existence in /tmp
+        run: ls -l /tmp/memory-cards-0.0.1-SNAPSHOT.jar
 
-        - name: Set up JDK 23
-          uses: actions/setup-java@v4
-          with:
-            java-version: '23'
-            distribution: 'temurin'
+      - name: Set up JDK 23
+        uses: actions/setup-java@v4
+        with:
+          java-version: '23'
+          distribution: 'temurin'
 
-        - name: Stop all running Java processes
-          run: |
-            echo "Killing all running Java processes..."
-            pkill -f java || echo "No Java processes running."
+      - name: Stop all running Java processes
+        run: |
+          echo "Killing all running Java processes..."
+          pkill -f java || echo "No Java processes running."
 
-        - name: Start application in background
-          env:
-            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
-          run: |
-            echo "Starting application in background with nohup..."
-            nohup java -jar /tmp/memory-cards-0.0.1-SNAPSHOT.jar > /tmp/app.log 2>&1 &
+      - name: Start application in background
+        env:
+          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          echo "Starting application in background with nohup..."
+          nohup java -jar /tmp/memory-cards-0.0.1-SNAPSHOT.jar > /tmp/app.log 2>&1 &
 
-        - name: Health Check
-          run: |
-            echo "Performing health check..."
-            sleep 20  # Letting the app to start
-            if pgrep -f memory-cards-0.0.1-SNAPSHOT.jar > /dev/null; then
-              echo "Application is running."
-            else
-              echo "Application failed to start."
-              exit 1
-            fi
+      - name: Health Check
+        run: |
+          echo "Performing health check..."
+          sleep 20  # Letting the app to start
+          if pgrep -f memory-cards-0.0.1-SNAPSHOT.jar > /dev/null; then
+            echo "Application is running."
+          else
+            echo "Application failed to start."
+            exit 1
+          fi
 
 #  dependency-submission:
 #    runs-on: self-hosted
